# Generated by Django 3.0.9 on 2020-08-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20200804_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Library'),
        ),
    ]
